validationData= [
    {'Name':'C1','recentActivity':{'socialMediaComment':'Thinking of buying an iPhone','productLike':'AirPods','recentPurchase':'iPhone'}},
    {'Name':'C2','recentActivity':{'socialMediaComment':'TV deals are great this week','productLike':'Soundbar','recentPurchase':'Smart TV'}},
    {'Name':'C3','recentActivity':{'socialMediaComment':'Looking for a new laptop','productLike':'Wireless mouse','recentPurchase':'Laptop'}},
    {'Name':'C1','recentActivity':{'socialMediaComment':'AirPods look cool','productLike':'iPhone case','recentPurchase':'AirPods'}},
    {'Name':'C2','recentActivity':{'socialMediaComment':'Should I get a smartwatch?','productLike':'Fitness tracker','recentPurchase':'Smartwatch'}},
    {'Name':'C3','recentActivity':{'socialMediaComment':'Searching for best DSLR cameras','productLike':'Camera bag','recentPurchase':'DSLR Camera'}},
    {'Name':'C1','recentActivity':{'socialMediaComment':'I need a gaming chair','productLike':'Gaming keyboard','recentPurchase':'Gaming chair'}},
    {'Name':'C2','recentActivity':{'socialMediaComment':'Thinking about buying a washing machine','productLike':'Detergent','recentPurchase':'Washing machine'}},
    {'Name':'C3','recentActivity':{'socialMediaComment':'Looking for refrigerator discounts','productLike':'Water purifier','recentPurchase':'Refrigerator'}},
    {'Name':'C1','recentActivity':{'socialMediaComment':'Should I buy a Kindle?','productLike':'Reading lamp','recentPurchase':'Kindle'}},
    {'Name':'C2','recentActivity':{'socialMediaComment':'Need recommendations for headphones','productLike':'Earbuds','recentPurchase':'Noise-canceling headphones'}},
    {'Name':'C3','recentActivity':{'socialMediaComment':'Thinking of upgrading my monitor','productLike':'Keyboard','recentPurchase':'4K Monitor'}},
    {'Name':'C1','recentActivity':{'socialMediaComment':'Looking at microwave ovens','productLike':'Cookbook','recentPurchase':'Microwave oven'}},
    {'Name':'C2','recentActivity':{'socialMediaComment':'I want a Bluetooth speaker','productLike':'Wireless charger','recentPurchase':'Bluetooth speaker'}},
    {'Name':'C3','recentActivity':{'socialMediaComment':'Electric scooters are fun','productLike':'Helmet','recentPurchase':'Electric scooter'}},
    {'Name':'C1','recentActivity':{'socialMediaComment':'Checking deals for vacuum cleaners','productLike':'Cleaning supplies','recentPurchase':'Vacuum cleaner'}},
    {'Name':'C2','recentActivity':{'socialMediaComment':'Best budget smartphones?','productLike':'Phone cover','recentPurchase':'Budget smartphone'}},
    {'Name':'C3','recentActivity':{'socialMediaComment':'Should I get an air fryer?','productLike':'Recipe book','recentPurchase':'Air fryer'}},
    {'Name':'C1','recentActivity':{'socialMediaComment':'Exploring gaming consoles','productLike':'Gaming headphones','recentPurchase':'PS5'}},
    {'Name':'C2','recentActivity':{'socialMediaComment':'Looking for smart home devices','productLike':'Smart bulb','recentPurchase':'Smart plug'}},
    {'Name':'C3','recentActivity':{'socialMediaComment':'Want to buy a tablet','productLike':'Stylus','recentPurchase':'Tablet'}},
    {'Name':'C1','recentActivity':{'socialMediaComment':'Comparing coffee machines','productLike':'Coffee beans','recentPurchase':'Espresso machine'}},
    {'Name':'C2','recentActivity':{'socialMediaComment':'Smart TVs are tempting','productLike':'Streaming device','recentPurchase':'Smart TV'}},
    {'Name':'C3','recentActivity':{'socialMediaComment':'Shopping for gaming laptops','productLike':'Gaming mouse','recentPurchase':'Gaming laptop'}},
    {'Name':'C1','recentActivity':{'socialMediaComment':'Thinking about fitness trackers','productLike':'Smartwatch','recentPurchase':'Fitness band'}},
    {'Name':'C2','recentActivity':{'socialMediaComment':'Looking at projectors','productLike':'Projector screen','recentPurchase':'4K projector'}},
    {'Name':'C3','recentActivity':{'socialMediaComment':'New oven or not?','productLike':'Baking tools','recentPurchase':'Convection oven'}},
    {'Name':'C1','recentActivity':{'socialMediaComment':'Browsing electric bikes','productLike':'Cycling gloves','recentPurchase':'Electric bike'}},
    {'Name':'C2','recentActivity':{'socialMediaComment':'Home theater setups','productLike':'Subwoofer','recentPurchase':'Home theater system'}},
    {'Name':'C3','recentActivity':{'socialMediaComment':'Should I buy a drone?','productLike':'Drone batteries','recentPurchase':'Camera drone'}},
    {'Name':'C1','recentActivity':{'socialMediaComment':'Portable chargers are handy','productLike':'Power bank','recentPurchase':'Portable charger'}},
    {'Name':'C2','recentActivity':{'socialMediaComment':'Shopping for hair dryers','productLike':'Hair brush','recentPurchase':'Hair dryer'}},
    {'Name':'C3','recentActivity':{'socialMediaComment':'Smart locks seem cool','productLike':'Doorbell camera','recentPurchase':'Smart lock'}},
    {'Name':'C1','recentActivity':{'socialMediaComment':'Gaming mouse suggestions?','productLike':'Mouse pad','recentPurchase':'Gaming mouse'}},
    {'Name':'C2','recentActivity':{'socialMediaComment':'Comparing air conditioners','productLike':'Curtains','recentPurchase':'Split AC'}},
    {'Name':'C3','recentActivity':{'socialMediaComment':'I want to upgrade my router','productLike':'WiFi extender','recentPurchase':'High-speed router'}},
    {'Name':'C1','recentActivity':{'socialMediaComment':'Looking for streaming devices','productLike':'Remote case','recentPurchase':'Amazon Fire Stick'}},
    {'Name':'C2','recentActivity':{'socialMediaComment':'Should I get a mechanical keyboard?','productLike':'Wrist rest','recentPurchase':'Mechanical keyboard'}},
    {'Name':'C3','recentActivity':{'socialMediaComment':'Home automation is the future','productLike':'Smart plug','recentPurchase':'Smart home hub'}}
]

